name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Setup PNPM
      uses: pnpm/action-setup@v6

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Generate Documentation
      run: pnpm doc

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
